spring:
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/socksdb
    username: Darkc
    password: 111111
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
