--liquibase formatted sql

--changeset Pdemenkov:1

DROP TABLE IF EXISTS sock;

--changeset Pdemenkov:2
CREATE TABLE IF NOT EXISTS sock
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    color      VARCHAR(255)                            NOT NULL,
    cottonPart SMALLINT                                NOT NULL,
    quantity   INTEGER                                 NOT NULL
);